-- name: CreateAccount :one
INSERT INTO accounts (  -- id will be auto-generated by an increment order, created-time is auto set as default value now()
  owner,
  balance,
  currency
) VALUES (
  $1, $2, $3
) RETURNING *;  -- let postgresql returns values of all columns includes 'id'


-- name: GetAccount :one
SELECT * FROM accounts
WHERE id = $1 LIMIT 1;

-- name: GetAccountForUpdate :one
SELECT * FROM accounts
WHERE id = $1 LIMIT 1
FOR NO KEY UPDATE;

-- name: ListAccount :many
SELECT * FROM accounts
ORDER BY id
LIMIT $1  --limit how many rows we want to get
OFFSET $2; --skip how many records before return results

-- name: UpdateAccount :one
UPDATE accounts
SET balance = $2
WHERE id = $1
RETURNING *;

-- name: AddAccountBalance :one
UPDATE accounts
SET balance = balance + sqlc.arg(amount)
WHERE id = sqlc.arg(id)
RETURNING *;


-- name: DeleteAccount :exec
DELETE FROM accounts
WHERE id = $1;